language: ruby
rvm:
  - 2.2.0
before_script:
  - mysql -e 'create database rmagic_test;'
script:
  - bundle exec rake spec
  - bundle exec cucumber
addons:
  code_climate:
    repo_token: 68543eec9a2981eaa79e05fb0afc34da8194006df3345dbf1210a5a67b783ca3 bundle exec rake
